/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.ProcesoCompra;

import Clases.Frames;

import Clases.*;
import com.mycompany.teachstorelj.*;
import java.text.DecimalFormat;
import java.time.Duration;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class GenerarTicketFrame extends javax.swing.JFrame {
    DecimalFormat fm = new DecimalFormat("#, ###");
    DefaultTableModel modeloProductoFisico  = new DefaultTableModel();
    DefaultTableModel modeloSDigital  = new DefaultTableModel();
    DefaultTableModel modeloProductoVenta  = new DefaultTableModel();

    Frames recargarPagina = new Frames();
    Empleado cajero = RegistroCajeroFrame.ticket.getCajero();
    Cliente cliente = RegistroCajeroFrame.ticket.getCliente();
    
    //Necesitamos el la lsita de productos fisicos y servicio digital
    List<ProductoFisico> listaProductos = TeachStoreLJ.inventario.listaProductos;
    List<ServicioDigital> listaServiciosDigitales = TeachStoreLJ.inventario.listaSDigitales;

    public GenerarTicketFrame() {
        initComponents();
        //Registramos el cajero encargado
        txtCajero.setText(cajero.toString());
        
        if(cliente == null){
            //Si no se registro cliente, aparecera como "No registrado"
            txtCliente.setText("No registrado");
        } else{
            //Si se a registrado cliente, lo registramos
            txtCliente.setText(cliente.toString());
        }
        
        //Agregar encabezados a la tabla de productos fisicos
        modeloProductoVenta.setRowCount(0);
        String encabezado [] = {"Producto", "Precio U/N", "Descuento %", "Cantidad", "Total"};
        modeloProductoVenta.setColumnIdentifiers(encabezado);

        
        //Para poder agrear los productos y servicios digitales a la lista:
        actualizarTablaProductosFisicos();
        actualizarTablaServicioDigital();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicio = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescuentoProductos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescuentoPorPuntos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescuentoPorCompras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDescuentoTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProductoVenta = new javax.swing.JTable();
        btnBorrarProductoVenta = new javax.swing.JButton();
        btnEditarCantidadVenta = new javax.swing.JButton();
        txtCantidadProductoVenta = new javax.swing.JTextField();
        panelEscogerProductos = new javax.swing.JPanel();
        comboEleccion = new javax.swing.JComboBox<>();
        panelProductoFisico = new javax.swing.JPanel();
        btnAgregarProductoFisico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductoFisico = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        panelServicioDigital = new javax.swing.JPanel();
        btnAgregarServicioDigital = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaServicioDigital = new javax.swing.JTable();
        btnInicio1 = new javax.swing.JButton();
        btnInicio2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCajero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(30, 30, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(1270, 630));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("TechStore");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Creando Ticket");

        jPanel3.setBackground(new java.awt.Color(70, 73, 75));
        jPanel3.setForeground(new java.awt.Color(70, 73, 75));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Ticket");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subtotal");

        txtSubtotal.setBackground(new java.awt.Color(153, 153, 153));
        txtSubtotal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Impuestos");

        txtIva.setBackground(new java.awt.Color(153, 153, 153));
        txtIva.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descuento Por Productos");

        txtDescuentoProductos.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoProductos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Decuento Puntos");

        txtDescuentoPorPuntos.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoPorPuntos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descuento Fidelidad");

        txtDescuentoPorCompras.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoPorCompras.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descuento Total");

        txtDescuentoTotal.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoTotal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total a pagar");

        txtTotal.setBackground(new java.awt.Color(153, 153, 153));
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBackground(new java.awt.Color(70, 73, 75));
        jScrollPane4.setForeground(new java.awt.Color(70, 73, 75));

        tablaProductoVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto/SD", "Precio U/N", "Descuento %", "Cantidad/Tecnico", "Total"
            }
        ));
        jScrollPane4.setViewportView(tablaProductoVenta);

        btnBorrarProductoVenta.setBackground(new java.awt.Color(39, 241, 82));
        btnBorrarProductoVenta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBorrarProductoVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrarProductoVenta.setText("Borrar");
        btnBorrarProductoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBorrarProductoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProductoVenta(evt);
            }
        });

        btnEditarCantidadVenta.setBackground(new java.awt.Color(39, 241, 82));
        btnEditarCantidadVenta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEditarCantidadVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarCantidadVenta.setText("Editar Cantidad");
        btnEditarCantidadVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEditarCantidadVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCantidadVenta(evt);
            }
        });

        txtCantidadProductoVenta.setBackground(new java.awt.Color(153, 153, 153));
        txtCantidadProductoVenta.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        txtCantidadProductoVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidadProductoVenta.setText("0");
        txtCantidadProductoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBorrarProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidadProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(14, 14, 14))
                                    .addComponent(txtIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDescuentoTotal)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDescuentoProductos, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtDescuentoPorPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtDescuentoPorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 190, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuentoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDescuentoPorPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(28, 28, 28))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDescuentoPorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelEscogerProductos.setBackground(new java.awt.Color(70, 73, 75));
        panelEscogerProductos.setForeground(new java.awt.Color(70, 73, 75));

        comboEleccion.setBackground(new java.awt.Color(102, 102, 102));
        comboEleccion.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        comboEleccion.setForeground(new java.awt.Color(255, 255, 255));
        comboEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto Fisico", "Servicio Digital" }));
        comboEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEleccionActionPerformed(evt);
            }
        });

        panelProductoFisico.setBackground(new java.awt.Color(62, 66, 68));

        btnAgregarProductoFisico.setBackground(new java.awt.Color(39, 241, 82));
        btnAgregarProductoFisico.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAgregarProductoFisico.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarProductoFisico.setText("Agregar");
        btnAgregarProductoFisico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAgregarProductoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoFisico(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(70, 73, 75));
        jScrollPane1.setForeground(new java.awt.Color(70, 73, 75));

        tablaProductoFisico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Descuento %", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(tablaProductoFisico);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(238, 238, 238));
        jLabel13.setText("Cantidad Producto");

        txtCantidadProducto.setBackground(new java.awt.Color(153, 153, 153));
        txtCantidadProducto.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        txtCantidadProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidadProducto.setText("1");
        txtCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductoFisicoLayout = new javax.swing.GroupLayout(panelProductoFisico);
        panelProductoFisico.setLayout(panelProductoFisicoLayout);
        panelProductoFisicoLayout.setHorizontalGroup(
            panelProductoFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoFisicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarProductoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        panelProductoFisicoLayout.setVerticalGroup(
            panelProductoFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoFisicoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelProductoFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoFisicoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelProductoFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarProductoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoFisicoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        btnAgregarServicioDigital.setBackground(new java.awt.Color(39, 241, 82));
        btnAgregarServicioDigital.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAgregarServicioDigital.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarServicioDigital.setText("Agregar");
        btnAgregarServicioDigital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAgregarServicioDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioDigital(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(70, 73, 75));
        jScrollPane2.setForeground(new java.awt.Color(70, 73, 75));

        tablaServicioDigital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Servicio Digital", "Precio", "Tecnico", "Duracion", "Disponible"
            }
        ));
        jScrollPane2.setViewportView(tablaServicioDigital);

        javax.swing.GroupLayout panelServicioDigitalLayout = new javax.swing.GroupLayout(panelServicioDigital);
        panelServicioDigital.setLayout(panelServicioDigitalLayout);
        panelServicioDigitalLayout.setHorizontalGroup(
            panelServicioDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelServicioDigitalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarServicioDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        panelServicioDigitalLayout.setVerticalGroup(
            panelServicioDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicioDigitalLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarServicioDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEscogerProductosLayout = new javax.swing.GroupLayout(panelEscogerProductos);
        panelEscogerProductos.setLayout(panelEscogerProductosLayout);
        panelEscogerProductosLayout.setHorizontalGroup(
            panelEscogerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscogerProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscogerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboEleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProductoFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelEscogerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEscogerProductosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelServicioDigital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelEscogerProductosLayout.setVerticalGroup(
            panelEscogerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscogerProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelProductoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(panelEscogerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscogerProductosLayout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(panelServicioDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(69, 69, 69)))
        );

        btnInicio1.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio1.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio1.setText("Inicio");
        btnInicio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio1(evt);
            }
        });

        btnInicio2.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInicio2.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio2.setText("Generar Pago");
        btnInicio2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio2(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("Cajero");

        txtCajero.setBackground(new java.awt.Color(153, 153, 153));
        txtCajero.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        txtCajero.setForeground(new java.awt.Color(255, 255, 255));
        txtCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajeroActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 238, 238));
        jLabel12.setText("Cliente");

        txtCliente.setBackground(new java.awt.Color(153, 153, 153));
        txtCliente.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelEscogerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)
                        .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEscogerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio

    }//GEN-LAST:event_btnInicio

    private void btnInicio1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio1
        JOptionPane.showMessageDialog(null, "AL VOLVER AL INICIO REINICIAS LA COMPRA", "REINICIANDO COMPRA", JOptionPane.WARNING_MESSAGE);
        //Pasamos a actualizar el stock
        for(Map.Entry<ProductoFisico, Integer> par : RegistroCajeroFrame.ticket.getDicProductosFisicos().entrySet()){
            actualizarStockProducto(par.getKey(), 0, par.getValue());
        }
        
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnInicio1

    private void btnInicio2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio2
       dispose();
       recargarPagina.recargarMetodosPago();
    }//GEN-LAST:event_btnInicio2

    private void txtCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajeroActionPerformed

    }//GEN-LAST:event_txtCajeroActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void comboEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEleccionActionPerformed
        String eleccion = comboEleccion.getSelectedItem().toString();
        if(eleccion.equals("Producto Fisico")){
            panelProductoFisico.setVisible(true);
            panelServicioDigital.setVisible(false);
        } else if(eleccion.equals("Servicio Digital")){
            panelProductoFisico.setVisible(false);
            panelServicioDigital.setVisible(true);
        }
    }//GEN-LAST:event_comboEleccionActionPerformed

    private void btnAgregarProductoFisico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoFisico
        int seleccion = tablaProductoFisico.getSelectedRow();
        int cantidadProducto = Integer.parseInt(txtCantidadProducto.getText());
        if(seleccion != -1){
            ProductoFisico productoFisico = (ProductoFisico) tablaProductoFisico.getValueAt(seleccion, 0);
            if(cantidadProducto > 0){
                if(RegistroCajeroFrame.ticket.getDicProductosFisicos().containsKey(productoFisico)){
                    JOptionPane.showMessageDialog(null, "EL PRODUCTO YA ESTA AGREGADO", "PRODUCTO YA REGISTRADO", JOptionPane.ERROR_MESSAGE);
                }else{
                    actualizarTablaVentaProducto(productoFisico, cantidadProducto);
                    txtCantidadProducto.setText("1");
                            
                    //Agregamos el producto a la OrdenCompra       
                    RegistroCajeroFrame.ticket.getDicProductosFisicos().put(productoFisico, cantidadProducto);
                    
                    //Al agregar el producto se debe actualizar el stock
                    actualizarStockProducto(productoFisico, cantidadProducto,0);
                    
                    //Cada que agregamos debemos actualizar al tabla y toda la parte del pago
                    actualizarTablaProductosFisicos();
                    actualizarPanel();
                }
                
            } else{
                JOptionPane.showMessageDialog(null, "CANTIDAD DEL PRODUCTO MENOR O IGUAL A 0", "CANTIDAD NO VALIDA", JOptionPane.ERROR_MESSAGE);
            }
        } else{
            JOptionPane.showMessageDialog(null, "NO HAZ SELECCIONADO NINGUN PRODUCTO", "PRODUCTO NO VALIDO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarProductoFisico

    private void txtCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoActionPerformed

    private void btnBorrarProductoVenta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProductoVenta
       int seleccion = tablaProductoVenta.getSelectedRow();
       
       if(seleccion != -1){
           ProductoFisico producto = (ProductoFisico) tablaProductoVenta.getValueAt(seleccion, 0);
           int cantidadAntigua = Integer.parseInt(tablaProductoVenta.getValueAt(seleccion, 3).toString());
           
           borrarProducto(seleccion);
           //Se borra el produco de la OrdenCompra
           RegistroCajeroFrame.ticket.getDicProductosFisicos().remove(producto);
           
           //Se debe actualizar el stock
           actualizarStockProducto(producto, 0, cantidadAntigua);
           
           //Cada que borramos debemos actualizar al tabla y toda la parte del pago
            actualizarTablaProductosFisicos();
            actualizarPanel();
       } else{
           JOptionPane.showMessageDialog(null, "NO HAZ SELECCIONADO NINGUN PRODUCTO", "PRODUCTO NO VALIDO", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnBorrarProductoVenta

    private void btnEditarCantidadVenta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCantidadVenta
        
        int cantidadNueva = Integer.parseInt(txtCantidadProductoVenta.getText());
        int seleccion = tablaProductoVenta.getSelectedRow();
        
        if(seleccion != -1){
            int cantidadAntigua = Integer.parseInt(tablaProductoVenta.getValueAt(seleccion, 3).toString());
        
            //Actualizar tambien total por cantidad
            ProductoFisico productoFisico = (ProductoFisico) tablaProductoVenta.getValueAt(seleccion, 0);
            double precio = productoFisico.getPrecio();
            double descuento =  precio * ((double)productoFisico.getDescuento()/100);
            double precioDescuento =  precio - descuento;
            double nuevoTotal = cantidadNueva*precioDescuento;
            
            if (cantidadNueva > 0){
                modeloProductoVenta.setValueAt(cantidadNueva, seleccion, 3);
                modeloProductoVenta.setValueAt(fm.format(nuevoTotal), seleccion, 4);
                
                tablaProductoVenta.clearSelection();
                txtCantidadProductoVenta.setText("0");
                
                //Editamos en ordenCompra
                RegistroCajeroFrame.ticket.getDicProductosFisicos().put(productoFisico, cantidadNueva);
                
                //Al editar la cantidad del producto debe actualizarse el stock
                actualizarStockProducto(productoFisico, cantidadNueva, cantidadAntigua);
                
                //Cada que editamos debemos actualizar al tabla y toda la parte del pago
                actualizarTablaProductosFisicos();
                actualizarPanel();
            } else{
                JOptionPane.showMessageDialog(null, "CANTIDAD DEL PRODUCTO MENOR O IGUAL A 0", "CANTIDAD NO VALIDA", JOptionPane.ERROR_MESSAGE);
            }
       } else{
           JOptionPane.showMessageDialog(null, "NO HAZ SELECCIONADO NINGUN PRODUCTO", "PRODUCTO NO VALIDO", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnEditarCantidadVenta

    private void txtCantidadProductoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoVentaActionPerformed

    private void btnAgregarServicioDigital(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioDigital
        int seleccion = tablaServicioDigital.getSelectedRow();
        if(seleccion != -1){
            ServicioDigital servicioDigital = (ServicioDigital) tablaProductoFisico.getValueAt(seleccion, 0);
            if(RegistroCajeroFrame.ticket.getListaProductosDigitales().contains(servicioDigital)){
                    JOptionPane.showMessageDialog(null, "EL SERVICIO YA ESTA AGREGADO", "SERVICIO YA REGISTRADO", JOptionPane.ERROR_MESSAGE);
            }else{
                actualizarTablaVentaServico(servicioDigital);
                            
                //Agregamos el servicio a la OrdenCompra       
                RegistroCajeroFrame.ticket.getListaProductosDigitales().add(servicioDigital);
                    
               //Cada que agregamos debemos actualizar al tabla y toda la parte del pago
               actualizarTablaServicioDigital();
               actualizarPanel();
            }
        } else{
            JOptionPane.showMessageDialog(null, "NO HAZ SELECCIONADO NINGUN SERVICIO", "SERVICIO NO VALIDO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarServicioDigital
    
    private void actualizarTablaProductosFisicos(){
        modeloProductoFisico.setRowCount(0);
        String encabezado [] = {"Producto", "Precio U/N", "Descuento %", "Disponible", };
        modeloProductoFisico.setColumnIdentifiers(encabezado);
        
        tablaProductoFisico.setModel(modeloProductoFisico);
        for(ProductoFisico producto:listaProductos){
            double precio = producto.getPrecio();
            String descuento = producto.getDescuento() + "%";
            int stock = producto.getStock();
            
            modeloProductoFisico.addRow(new Object[] {producto, fm.format(precio), descuento, stock});
           
        }
    }
    
    private void actualizarTablaServicioDigital(){
        modeloSDigital.setRowCount(0);
        String encabezado2 [] = {"Servicio Digital", "Precio", "Tecnico Responsable", "Duracion", "Disponible"};
        modeloSDigital.setColumnIdentifiers(encabezado2);
        
        tablaServicioDigital.setModel(modeloSDigital);
        for(ServicioDigital servicio:listaServiciosDigitales){
            double precio = servicio.getPrecio();
            Tecnico tecnico = servicio.getTecnicoResponsable();
            String duracion = (String.valueOf(servicio.getDuracionEstimada().toMinutes()));
            String disponible = tecnico.getDisponibilidad();
            
            modeloSDigital.addRow(new Object[] {servicio, fm.format(precio), tecnico, duracion, disponible});
        }
    }
         
    
    private void actualizarTablaVentaProducto(ProductoFisico producto, int cantidad){
        tablaProductoVenta.setModel(modeloProductoVenta);
        double precio = (producto.getPrecio());
        double precioIva = (producto.getPrecio() / 1.19);
        double iva = precioIva * 0.19;
        double descuento =  precioIva * ((double)producto.getDescuento()/100);
        double precioDescuento =  precioIva - descuento;
        String descuentoVer = producto.getDescuento() + "%";
        double totalConDescuento = (precioDescuento + iva )* cantidad;
            
        modeloProductoVenta.addRow(new Object[] {producto, fm.format(precio), descuentoVer, cantidad,  fm.format(totalConDescuento)});
    }
    
    private void actualizarTablaVentaServico(ServicioDigital servicio){
        
    }
    
    private void borrarProducto(int seleccion){
        modeloProductoVenta.removeRow(seleccion);
    }
    
    private void actualizarStockProducto(ProductoFisico producto, int cantidad, int cantidadAntigua){
        int stock = producto.getStock() + cantidadAntigua;
        int nuevoStock = stock - cantidad;
        
        producto.modificarStock(nuevoStock);
    }
    
    private void actualizarSubtotal(){
        RegistroCajeroFrame.ticket.setSubtotal();
        double subtotal = RegistroCajeroFrame.ticket.getSubtotal();
        txtSubtotal.setText(fm.format(subtotal));
    }
    
    private void actualizarImpuestos(){
        RegistroCajeroFrame.ticket.setIva();
        double impuesto = RegistroCajeroFrame.ticket.getIva();
        txtIva.setText(fm.format(impuesto));
    }

    private void actualizarTotal(){
        RegistroCajeroFrame.ticket.setTotal();
        double total = RegistroCajeroFrame.ticket.getTotal();
        txtTotal.setText(fm.format(total));
    }
    
    private void actualizarDescuentoPorProductos(){
        RegistroCajeroFrame.ticket.setDescuentoPorLotes();
        double descuentoPorLotes = RegistroCajeroFrame.ticket.getDescuentoPorLotes();
        txtDescuentoProductos.setText(fm.format(descuentoPorLotes));
    }
    
    private void actualizarDescuentoPorPuntos(){
        RegistroCajeroFrame.ticket.setDescuentoPuntos();
        double descuentoPorPuntos = RegistroCajeroFrame.ticket.getDescuentoPuntos();
        txtDescuentoPorPuntos.setText(fm.format(descuentoPorPuntos));
    }
    
    private void actualizarDescuentoPorCompras(){
        RegistroCajeroFrame.ticket.setDescuentoPorFidelidad();
        double descuentoPorCompras =  RegistroCajeroFrame.ticket.getDescuentoPorFidelidad();
        txtDescuentoPorCompras.setText(fm.format(descuentoPorCompras));
    }
    
    private void actualizarDescuentoTotal(){
        RegistroCajeroFrame.ticket.setDescuentoTotal();
        double descuentoTotal =  RegistroCajeroFrame.ticket.getDescuentoTotal();
        txtDescuentoTotal.setText(fm.format(descuentoTotal));
    }
    
    private void actualizarPanel(){
        actualizarSubtotal();
        actualizarImpuestos();
        actualizarDescuentoPorProductos();
        actualizarDescuentoPorPuntos();
        actualizarDescuentoPorCompras();
        actualizarDescuentoTotal();
        actualizarTotal();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductoFisico;
    private javax.swing.JButton btnAgregarServicioDigital;
    private javax.swing.JButton btnBorrarProductoVenta;
    private javax.swing.JButton btnEditarCantidadVenta;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInicio1;
    private javax.swing.JButton btnInicio2;
    private javax.swing.JComboBox<String> comboEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelEscogerProductos;
    private javax.swing.JPanel panelProductoFisico;
    private javax.swing.JPanel panelServicioDigital;
    private javax.swing.JTable tablaProductoFisico;
    private javax.swing.JTable tablaProductoVenta;
    private javax.swing.JTable tablaServicioDigital;
    private javax.swing.JTextField txtCajero;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCantidadProductoVenta;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescuentoPorCompras;
    private javax.swing.JTextField txtDescuentoPorPuntos;
    private javax.swing.JTextField txtDescuentoProductos;
    private javax.swing.JTextField txtDescuentoTotal;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
