/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.ProcesoCompra;

import Clases.*;
import MeException.*;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class MetodoDePagoFrame extends javax.swing.JFrame {
    public static Factura factura;

    Frames recargarPagina = new Frames();
    DefaultTableModel modeloProductoVenta  = new DefaultTableModel();
    DecimalFormat fm = new DecimalFormat("#, ###");

    Empleado cajero = RegistroCajeroFrame.ticket.getCajero();
    Cliente cliente = RegistroCajeroFrame.ticket.getCliente();
    
    GenerarTicketFrame ordenCompra = new GenerarTicketFrame();
    
    
    public MetodoDePagoFrame() {
        initComponents();
        btnFacturar.setVisible(false);
        
        comboMetodosPago.setSelectedItem("Efectivo");
        
        //Agregamos a la tabla la factura final
        actualizarFactura();
        
        //Registramos el cajero encargado
        txtCajero.setText(cajero.toString());
        
        if(cliente == null){
            //Si no se registro cliente, aparecera como "No registrado"
            txtCliente.setText("No registrado");
        } else{
            //Si se a registrado cliente, lo registramos
            txtCliente.setText(cliente.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboMetodosPago = new javax.swing.JComboBox<>();
        panelDidactico = new javax.swing.JPanel();
        panelEfectivo13 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        totalDevolver = new javax.swing.JTextField();
        panelTarjetaCredito = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        comboCuotas = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        txtRecargo = new javax.swing.JTextField();
        txtValidarCredito = new javax.swing.JTextField();
        totall2 = new javax.swing.JLabel();
        panelTarjetaDebito = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        txtDebito = new javax.swing.JTextField();
        totall = new javax.swing.JLabel();
        txtDebitoTotal = new javax.swing.JTextField();
        txtValidarDebito = new javax.swing.JTextField();
        totall1 = new javax.swing.JLabel();
        panelTransferencia = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        txtTransferencia = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txtValidarTransferencia = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescuentoProductos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescuentoPorPuntos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescuentoPorCompras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDescuentoTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProductoVenta = new javax.swing.JTable();
        txtCajero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(30, 30, 46));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("TechStore");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Metodo de Pago");

        jPanel5.setBackground(new java.awt.Color(70, 73, 75));
        jPanel5.setForeground(new java.awt.Color(70, 73, 75));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("Elige un metodo de pago");

        comboMetodosPago.setBackground(new java.awt.Color(102, 102, 102));
        comboMetodosPago.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        comboMetodosPago.setForeground(new java.awt.Color(255, 255, 255));
        comboMetodosPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta Credito", "Tarjeta Debito", "Transferencia" }));
        comboMetodosPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMetodosPagoActionPerformed(evt);
            }
        });

        panelDidactico.setBackground(new java.awt.Color(70, 73, 75));

        panelEfectivo13.setBackground(new java.awt.Color(70, 73, 75));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(238, 238, 238));
        jLabel39.setText("Ingresa el efectivo recibido");

        jTextField34.setBackground(new java.awt.Color(153, 153, 153));
        jTextField34.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        jTextField34.setForeground(new java.awt.Color(255, 255, 255));
        jTextField34.setText("0");

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(238, 238, 238));
        jLabel40.setText("Total a devolver");

        totalDevolver.setBackground(new java.awt.Color(153, 153, 153));
        totalDevolver.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        totalDevolver.setForeground(new java.awt.Color(255, 255, 255));
        totalDevolver.setText("0");

        javax.swing.GroupLayout panelEfectivo13Layout = new javax.swing.GroupLayout(panelEfectivo13);
        panelEfectivo13.setLayout(panelEfectivo13Layout);
        panelEfectivo13Layout.setHorizontalGroup(
            panelEfectivo13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivo13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEfectivo13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(totalDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEfectivo13Layout.setVerticalGroup(
            panelEfectivo13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivo13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        panelTarjetaCredito.setBackground(new java.awt.Color(70, 73, 75));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(238, 238, 238));
        jLabel41.setText("Ingresa el numero de la tarjeta credito");

        txtCredito.setBackground(new java.awt.Color(153, 153, 153));
        txtCredito.setFont(new java.awt.Font("Baloo 2", 0, 10)); // NOI18N
        txtCredito.setForeground(new java.awt.Color(255, 255, 255));
        txtCredito.setText("0");

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(238, 238, 238));
        jLabel42.setText("Escoge el total de cuotas");

        comboCuotas.setBackground(new java.awt.Color(153, 153, 153));
        comboCuotas.setFont(new java.awt.Font("Baloo 2", 0, 10)); // NOI18N
        comboCuotas.setForeground(new java.awt.Color(255, 255, 255));
        comboCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "6", "12" }));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(238, 238, 238));
        jLabel43.setText("Total recargo");

        txtRecargo.setBackground(new java.awt.Color(153, 153, 153));
        txtRecargo.setFont(new java.awt.Font("Baloo 2", 0, 10)); // NOI18N
        txtRecargo.setForeground(new java.awt.Color(255, 255, 255));
        txtRecargo.setText("0");

        txtValidarCredito.setBackground(new java.awt.Color(153, 153, 153));
        txtValidarCredito.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtValidarCredito.setForeground(new java.awt.Color(255, 255, 255));

        totall2.setBackground(new java.awt.Color(255, 255, 255));
        totall2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        totall2.setForeground(new java.awt.Color(238, 238, 238));
        totall2.setText("Validacion Tarjeta");

        javax.swing.GroupLayout panelTarjetaCreditoLayout = new javax.swing.GroupLayout(panelTarjetaCredito);
        panelTarjetaCredito.setLayout(panelTarjetaCreditoLayout);
        panelTarjetaCreditoLayout.setHorizontalGroup(
            panelTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaCreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jLabel41)
                        .addComponent(jLabel42)
                        .addComponent(comboCuotas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRecargo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jLabel43))
                    .addGroup(panelTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtValidarCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(totall2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelTarjetaCreditoLayout.setVerticalGroup(
            panelTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaCreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totall2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValidarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelTarjetaDebito.setBackground(new java.awt.Color(70, 73, 75));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(238, 238, 238));
        jLabel45.setText("Ingresa el numero de la tarjeta debito");

        txtDebito.setBackground(new java.awt.Color(153, 153, 153));
        txtDebito.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtDebito.setForeground(new java.awt.Color(255, 255, 255));
        txtDebito.setText("0");

        totall.setBackground(new java.awt.Color(255, 255, 255));
        totall.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        totall.setForeground(new java.awt.Color(238, 238, 238));
        totall.setText("Total");

        txtDebitoTotal.setBackground(new java.awt.Color(153, 153, 153));
        txtDebitoTotal.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtDebitoTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtDebitoTotal.setText("0");

        txtValidarDebito.setBackground(new java.awt.Color(153, 153, 153));
        txtValidarDebito.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtValidarDebito.setForeground(new java.awt.Color(255, 255, 255));

        totall1.setBackground(new java.awt.Color(255, 255, 255));
        totall1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        totall1.setForeground(new java.awt.Color(238, 238, 238));
        totall1.setText("Validacion Tarjeta");

        javax.swing.GroupLayout panelTarjetaDebitoLayout = new javax.swing.GroupLayout(panelTarjetaDebito);
        panelTarjetaDebito.setLayout(panelTarjetaDebitoLayout);
        panelTarjetaDebitoLayout.setHorizontalGroup(
            panelTarjetaDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaDebitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarjetaDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarjetaDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jLabel45))
                    .addGroup(panelTarjetaDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDebitoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(totall))
                    .addGroup(panelTarjetaDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtValidarDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(totall1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelTarjetaDebitoLayout.setVerticalGroup(
            panelTarjetaDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaDebitoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(totall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDebitoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(totall1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValidarDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        panelTransferencia.setBackground(new java.awt.Color(70, 73, 75));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(238, 238, 238));
        jLabel47.setText("Ingresa el numero de referencia ");

        txtTransferencia.setBackground(new java.awt.Color(153, 153, 153));
        txtTransferencia.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        txtTransferencia.setText("0");

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(238, 238, 238));
        jLabel48.setText("Validacion Transferencia");

        txtValidarTransferencia.setBackground(new java.awt.Color(153, 153, 153));
        txtValidarTransferencia.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtValidarTransferencia.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTransferenciaLayout = new javax.swing.GroupLayout(panelTransferencia);
        panelTransferencia.setLayout(panelTransferenciaLayout);
        panelTransferenciaLayout.setHorizontalGroup(
            panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jLabel47))
                    .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtValidarTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jLabel48)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelTransferenciaLayout.setVerticalGroup(
            panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferenciaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValidarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDidacticoLayout = new javax.swing.GroupLayout(panelDidactico);
        panelDidactico.setLayout(panelDidacticoLayout);
        panelDidacticoLayout.setHorizontalGroup(
            panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDidacticoLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(panelEfectivo13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDidacticoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTarjetaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTarjetaDebito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTransferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDidacticoLayout.setVerticalGroup(
            panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDidacticoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelEfectivo13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDidacticoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTarjetaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTarjetaDebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDidacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEnviar.setBackground(new java.awt.Color(39, 241, 82));
        btnEnviar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(0, 0, 0));
        btnEnviar.setText("Enviar");
        btnEnviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar(evt);
            }
        });

        btnFacturar.setBackground(new java.awt.Color(39, 241, 82));
        btnFacturar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnFacturar.setForeground(new java.awt.Color(0, 0, 0));
        btnFacturar.setText("Facturar");
        btnFacturar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturar(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelDidactico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDidactico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(70, 73, 75));
        jPanel3.setForeground(new java.awt.Color(70, 73, 75));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Ticket");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subtotal");

        txtSubtotal.setBackground(new java.awt.Color(153, 153, 153));
        txtSubtotal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Impuestos");

        txtIva.setBackground(new java.awt.Color(153, 153, 153));
        txtIva.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descuento Por Productos");

        txtDescuentoProductos.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoProductos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Decuento Puntos");

        txtDescuentoPorPuntos.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoPorPuntos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descuento Fidelidad");

        txtDescuentoPorCompras.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoPorCompras.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descuento Total");

        txtDescuentoTotal.setBackground(new java.awt.Color(153, 153, 153));
        txtDescuentoTotal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total a pagar");

        txtTotal.setBackground(new java.awt.Color(153, 153, 153));
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBackground(new java.awt.Color(70, 73, 75));
        jScrollPane4.setForeground(new java.awt.Color(70, 73, 75));

        tablaProductoVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto/SD", "Precio U/N", "Descuento %", "Cantidad/Tecnico", "Total"
            }
        ));
        jScrollPane4.setViewportView(tablaProductoVenta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(14, 14, 14))
                                    .addComponent(txtIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDescuentoTotal)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDescuentoProductos, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtDescuentoPorPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtDescuentoPorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 413, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuentoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDescuentoPorPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(28, 28, 28))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDescuentoPorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtCajero.setBackground(new java.awt.Color(153, 153, 153));
        txtCajero.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        txtCajero.setForeground(new java.awt.Color(255, 255, 255));
        txtCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajeroActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 238, 238));
        jLabel12.setText("Cajero");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(238, 238, 238));
        jLabel13.setText("Cliente");

        txtCliente.setBackground(new java.awt.Color(153, 153, 153));
        txtCliente.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio
        JOptionPane.showMessageDialog(null, "AL VOLVER AL INICIO REINICIAS LA COMPRA", "REINICIANDO COMPRA", JOptionPane.WARNING_MESSAGE);
        //Pasamos a actualizar el stock
        for(Map.Entry<ProductoFisico, Integer> par : RegistroCajeroFrame.ticket.getDicProductosFisicos().entrySet()){
            ordenCompra.actualizarStockProducto(par.getKey(), 0, par.getValue());
        }
        //Y actualizar la disponibilidad de los tecnicos
        for(Map.Entry<ServicioDigital, LocalDateTime> par : RegistroCajeroFrame.ticket.getDicServiciosDigitales().entrySet()){
            ServicioDigital servicio = par.getKey();
            Tecnico tecnico = servicio.getTecnicoResponsable();
            tecnico.agendarServicio(LocalDateTime.now().minusMinutes(1));
        }
        
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnInicio

    private void comboMetodosPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMetodosPagoActionPerformed
        panelEfectivo13.setVisible(false);
        panelTarjetaCredito.setVisible(false);
        panelTarjetaDebito.setVisible(false);
        panelTransferencia.setVisible(false);

        String opcion = comboMetodosPago.getSelectedItem().toString();

        switch (opcion) {
            case "Efectivo":
            panelEfectivo13.setVisible(true);
            break;
            case "Tarjeta Credito":
            panelTarjetaCredito.setVisible(true);
            break;
            case "Tarjeta Debito":
            panelTarjetaDebito.setVisible(true);
            break;
            case "Transferencia":
            panelTransferencia.setVisible(true);
            break;
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_comboMetodosPagoActionPerformed

    
    private void actualizarFactura(){
        HashMap<ProductoFisico, Integer> productosFisicos = RegistroCajeroFrame.ticket.getDicProductosFisicos();
        HashMap<ServicioDigital, LocalDateTime> serviciosDigitales = RegistroCajeroFrame.ticket.getDicServiciosDigitales();
        
        tablaProductoVenta.setModel(modeloProductoVenta);
        modeloProductoVenta.setRowCount(0);
        String encabezado [] = {"Producto/SD", "Precio U/N", "Des %/Hora Fin", "Cantidad/Tecnico", "Total"};
        modeloProductoVenta.setColumnIdentifiers(encabezado);
        
        //Agregamos los productosFisicos
        for(Map.Entry<ProductoFisico, Integer> par : productosFisicos.entrySet()){
            ProductoFisico producto = par.getKey();
            int cantidad = par.getValue();
            double precio = producto.getPrecio();
            String descuento = producto.getDescuento()+ "%";
            double total = producto.getTotalProducto(cantidad);
            modeloProductoVenta.addRow(new Object[] {producto, fm.format(precio), descuento, cantidad,  fm.format(total)});
        }
        
        //Agregamos Servicios Digitales
        for(Map.Entry<ServicioDigital, LocalDateTime> par : serviciosDigitales.entrySet()){
            ServicioDigital servicio = par.getKey();
            double precio = servicio.getPrecio();
            Tecnico tecnico = servicio.getTecnicoResponsable();
            String duracion = (String.valueOf(servicio.getDuracionEstimada().toMinutes()));
            
            modeloProductoVenta.addRow(new Object[] {servicio, fm.format(precio), tecnico, duracion, fm.format(precio)});
        }
        
        //Ingresamos subtotal - impuesto - descuentos y total
        txtSubtotal.setText(fm.format(RegistroCajeroFrame.ticket.getSubtotal()));
        txtIva.setText(fm.format(RegistroCajeroFrame.ticket.getIva()));
        txtDescuentoProductos.setText(fm.format(RegistroCajeroFrame.ticket.getDescuentoPorLotes()));
        txtDescuentoPorPuntos.setText(fm.format(RegistroCajeroFrame.ticket.getDescuentoPuntos()));
        txtDescuentoPorCompras.setText(fm.format(RegistroCajeroFrame.ticket.getDescuentoPorFidelidad()));
        txtDescuentoTotal.setText(fm.format(RegistroCajeroFrame.ticket.getDescuentoTotal()));
        txtTotal.setText(fm.format(RegistroCajeroFrame.ticket.getTotal()));
    }
    
    private void txtCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajeroActionPerformed

    }//GEN-LAST:event_txtCajeroActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnEnviar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar
        String seleccion = comboMetodosPago.getSelectedItem().toString();
        String clienteFactura = "No registrado";
        if(cliente != null){
            clienteFactura = cliente.toString();
        } 
        
        double totalPagar = RegistroCajeroFrame.ticket.getTotal();
        switch (seleccion) {
            case "Efectivo":
                try{
                    Efectivo efectivo = new Efectivo(totalPagar, "Efectivo", "Pendiente");
                    String precioF = jTextField34.getText();
                    double efectivoRecibido = recargarPagina.convertirPrecio(precioF);
                    double devuelta = efectivoRecibido - totalPagar;
                    efectivo.setTotalRecibido(efectivoRecibido);
                    efectivo.setTotalPagar(devuelta);
                    totalDevolver.setText(fm.format(devuelta));
                    
                    //Por ultimo se genera la factura (final)
                    factura = new Factura(RegistroCajeroFrame.ticket, efectivo);
                    //Como todo sale bien con el pago ya puede facturar
                    btnFacturar.setVisible(true);
                } catch(PagoEfectivoRechazadoException e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "COMPRA NO VALIDA", JOptionPane.ERROR_MESSAGE);
                }
            break;
            case "Tarjeta Credito":
                try{
                   long numeroTarjeta = Long.parseLong(txtCredito.getText());
                   int cuotas = Integer.parseInt(comboCuotas.getSelectedItem().toString());
                   TarjetaCredito credito = new TarjetaCredito(numeroTarjeta, cuotas, totalPagar, "Tarjeta Credito", "Pendiente");
                   credito.setTotalRecargo();
                   txtRecargo.setText(fm.format(credito.getTotalRecargo()));
                   txtValidarCredito.setText("Tarjeta Aceptada");
                   
                   //Por ultimo se genera la factura (final)
                   factura = new Factura(RegistroCajeroFrame.ticket, credito);
                    //Como todo sale bien con el pago ya puede facturar
                    btnFacturar.setVisible(true);
                } catch(TarjetaRechazadaException e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "COMPRA NO VALIDA", JOptionPane.ERROR_MESSAGE);
                    txtValidarCredito.setText("Tarjeta Rechazada");
                } catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "VERIFICA QUE INGRESASTE UN NUMERO", "NUMERO NO VALIDO", JOptionPane.ERROR_MESSAGE);
                    txtValidarCredito.setText("Tarjeta Rechazada");
                }
            break;
            case "Tarjeta Debito":
                try{
                   long numeroTarjeta = Long.parseLong(txtDebito.getText());
                   TarjetaDebito debito = new TarjetaDebito(numeroTarjeta, totalPagar, "Tarjeta Debito", "Pendiente");
                   txtDebitoTotal.setText(fm.format(totalPagar));
                   txtValidarDebito.setText("Tarjeta Aceptada");
                   
                   //Por ultimo se genera la factura (final)
                   factura = new Factura(RegistroCajeroFrame.ticket, debito);
                    //Como todo sale bien con el pago ya puede facturar
                    btnFacturar.setVisible(true);
                } catch(TarjetaRechazadaException e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "COMPRA NO VALIDA", JOptionPane.ERROR_MESSAGE);
                    txtValidarDebito.setText("Tarjeta Rechazada");
                } catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "VERIFICA QUE INGRESASTE UN NUMERO", "NUMERO NO VALIDO", JOptionPane.ERROR_MESSAGE);
                    txtValidarCredito.setText("Tarjeta Rechazada");
                }
                break;
            case "Transferencia":
                try{
                   long numeroTransferencia = Long.parseLong(txtTransferencia.getText());
                   Transferencia transferencia = new Transferencia(numeroTransferencia, totalPagar, "Transferencia", "Pendiente");
                   txtValidarTransferencia.setText("Tarjeta Aceptada");
                   
                   //Por ultimo se genera la factura (final)
                   factura = new Factura(RegistroCajeroFrame.ticket, transferencia);
                    //Como todo sale bien con el pago ya puede facturar
                    btnFacturar.setVisible(true);
                } catch(TransferenciaRechazadaException e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "COMPRA NO VALIDA", JOptionPane.ERROR_MESSAGE);
                    txtValidarTransferencia.setText("Transferencia Rechazada");
                } catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "VERIFICA QUE INGRESASTE UN NUMERO", "NUMERO NO VALIDO", JOptionPane.ERROR_MESSAGE);
                    txtValidarCredito.setText("Transferencia Rechazada");
                }
            break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnEnviar

    private void btnFacturar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturar
        dispose();
        recargarPagina.recargarFactura();
    }//GEN-LAST:event_btnFacturar



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JComboBox<String> comboCuotas;
    private javax.swing.JComboBox<String> comboMetodosPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JPanel panelDidactico;
    private javax.swing.JPanel panelEfectivo13;
    private javax.swing.JPanel panelTarjetaCredito;
    private javax.swing.JPanel panelTarjetaDebito;
    private javax.swing.JPanel panelTransferencia;
    private javax.swing.JTable tablaProductoVenta;
    private javax.swing.JTextField totalDevolver;
    private javax.swing.JLabel totall;
    private javax.swing.JLabel totall1;
    private javax.swing.JLabel totall2;
    private javax.swing.JTextField txtCajero;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtDebito;
    private javax.swing.JTextField txtDebitoTotal;
    private javax.swing.JTextField txtDescuentoPorCompras;
    private javax.swing.JTextField txtDescuentoPorPuntos;
    private javax.swing.JTextField txtDescuentoProductos;
    private javax.swing.JTextField txtDescuentoTotal;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtRecargo;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTransferencia;
    private javax.swing.JTextField txtValidarCredito;
    private javax.swing.JTextField txtValidarDebito;
    private javax.swing.JTextField txtValidarTransferencia;
    // End of variables declaration//GEN-END:variables
}
