
package GUI.ProcesoCompra;

import Clases.*;
import com.mycompany.teachstorelj.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RegistroClienteFrame extends javax.swing.JFrame {
    Frames recargarPagina = new Frames();   
    DefaultTableModel mt  = new DefaultTableModel();
    List<Cliente> listaClientes = TeachStoreLJ.usuarios.listaClientes;
    

    public RegistroClienteFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btnVentaSinCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscaCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("TechStore");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Cliente");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("Documento");

        txtDocumento.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N

        btnRegistrarCliente.setBackground(new java.awt.Color(39, 241, 82));
        btnRegistrarCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio(evt);
            }
        });

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Identificacion", "Contacto", "Correo Electronico", "Direccion", "ID"
            }
        ));
        jScrollPane5.setViewportView(tablaCliente);

        btnVentaSinCliente.setBackground(new java.awt.Color(39, 241, 82));
        btnVentaSinCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnVentaSinCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnVentaSinCliente.setText("Venta Sin Cliente");
        btnVentaSinCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVentaSinCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaSinClienteActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("-> Si desea registrar cliente, ingrese su documento y seleccione el boton Registrar Cliente");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("-> Si el cliente no esta registrado, seleccione el boton Venta Sin Cliente");

        btnBuscaCliente.setBackground(new java.awt.Color(39, 241, 82));
        btnBuscaCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBuscaCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscaCliente.setText("Buscar Cliente");
        btnBuscaCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCliente(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVentaSinCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 210, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentaSinCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio
        //Boton volver a inicio
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnInicio

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        String documento = txtDocumento.getText();
        boolean registroValido = false;
        
        for(Cliente cliente:listaClientes){
            if(cliente.getCedula().equals(documento)){
                registroValido = true;
                JOptionPane.showMessageDialog(null, "BIENVENIDO " + cliente.getNombre(), "REGISTRO CLIENTE EXICTOSO", JOptionPane.HEIGHT);
                //Agregamos al ticket el cliente que va a realizar la venta
                RegistroCajeroFrame.ticket.setCliente(cliente);
                dispose();
                recargarPagina.recargarCrearTicket(); 
            }
        }
        if (registroValido == false){
            JOptionPane.showMessageDialog(null, "REGISTRO NO VALIDO", "CLIENTE NO VALIDO", JOptionPane.ERROR_MESSAGE);
            dispose();
            recargarPagina.recargarRegistrarCajero();
        }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnVentaSinClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaSinClienteActionPerformed
        //Ahora si la venta no ser egistra cliente, simplemente pasa a generar ticket
        dispose();
        recargarPagina.recargarCrearTicket(); 
    }//GEN-LAST:event_btnVentaSinClienteActionPerformed

    private void btnBuscaCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCliente
        String documento = txtDocumento.getText();
        for(Cliente cliente:listaClientes){
            if(cliente.getCedula().equals(documento)){
                //Cada que busca un cliente se muestra la info de este en la tabla
                mt.setRowCount(0);
                String encabezado [] = {"Nombre", "Identificacion", "Contacto", "Correo Electronico", "Direccion", "ID"};
                mt.setColumnIdentifiers(encabezado);

                tablaCliente.setModel(mt);

                //DATOS CLIENTE
                String nombre = cliente.getNombre();
                String cedula = cliente.getCedula();
                String telefono = cliente.getTelefono();
                String direccion = cliente.getDireccion();
                String email = cliente.getCorreo();
                String id = cliente.getId();

                mt.addRow(new Object[] {nombre, cedula, telefono, email, direccion, id});
            }
        }
    }//GEN-LAST:event_btnBuscaCliente


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCliente;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnVentaSinCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
