/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Empleados;

import Clases.*;
import javax.swing.table.DefaultTableModel;

import Clases.*;
import java.util.*;
import com.mycompany.teachstorelj.TeachStoreLJ;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

public class VerEmpleadosFrame extends javax.swing.JFrame {
    DefaultTableModel mt  = new DefaultTableModel();
    Frames recargarPagina = new Frames();
    public VerEmpleadosFrame() {
        initComponents();
        
        actualizarTabla();
        
        //Agregamos los items al filtro de salario
        comboSalario.addItem("Minimo");
        comboSalario.addItem("$1.500.000 $1.999.999");
        comboSalario.addItem("$2.000.000 - $2.999.999");
        comboSalario.addItem("$3.000.000 - $4.999.999");
        comboSalario.addItem("$5.000.000 - $9.999.999");
        comboSalario.addItem("$10.000.000 o más"); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        btnInicio = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        comboJornada = new javax.swing.JComboBox<>();
        txtIdentificacion = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtProfesion = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        comboCargo = new javax.swing.JComboBox<>();
        comboSalario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("TechStore");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("Empleados");

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Identificacion", "Contacto", "Correo Electronico", "Cargo", "Salario", "Profesion", "Jornada Laboral", "Id     "
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(59, 63, 66));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKetReleased(evt);
            }
        });

        comboJornada.setBackground(new java.awt.Color(59, 63, 66));
        comboJornada.setForeground(new java.awt.Color(255, 255, 255));
        comboJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Tiempo Completo", "Medio Tiempo" }));
        comboJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJornadaActionPerformed(evt);
            }
        });

        txtIdentificacion.setBackground(new java.awt.Color(59, 63, 66));
        txtIdentificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdentificacionKetReleased(evt);
            }
        });

        txtContacto.setBackground(new java.awt.Color(59, 63, 66));
        txtContacto.setForeground(new java.awt.Color(255, 255, 255));
        txtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoActionPerformed(evt);
            }
        });
        txtContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactoKetReleased(evt);
            }
        });

        txtCorreo.setBackground(new java.awt.Color(59, 63, 66));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKetReleased(evt);
            }
        });

        txtProfesion.setBackground(new java.awt.Color(59, 63, 66));
        txtProfesion.setForeground(new java.awt.Color(255, 255, 255));
        txtProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfesionActionPerformed(evt);
            }
        });
        txtProfesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProfesionKetReleased(evt);
            }
        });

        txtId.setBackground(new java.awt.Color(59, 63, 66));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("EMP-00");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKetReleased(evt);
            }
        });

        comboCargo.setBackground(new java.awt.Color(59, 63, 66));
        comboCargo.setForeground(new java.awt.Color(255, 255, 255));
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Cajero", "Tecnico", "Supervisor", " " }));
        comboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargoActionPerformed(evt);
            }
        });

        comboSalario.setBackground(new java.awt.Color(59, 63, 66));
        comboSalario.setForeground(new java.awt.Color(255, 255, 255));
        comboSalario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        comboSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalarioActionPerformed(evt);
            }
        });
        comboSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VerEmpleadosFrame.this.keyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 1184, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        //Boton inicio
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtNombreKetReleased

    private void comboJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJornadaActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_comboJornadaActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtIdentificacionKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtIdentificacionKetReleased

    private void txtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtContactoActionPerformed

    private void txtContactoKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtContactoKetReleased

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtCorreoKetReleased

    private void txtProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfesionActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtProfesionActionPerformed

    private void txtProfesionKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProfesionKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtProfesionKetReleased

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtIdKetReleased

    private void comboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargoActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_comboCargoActionPerformed

    private void comboSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalarioActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_comboSalarioActionPerformed

    private void keyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyReleased
       actualizarTabla();
    }//GEN-LAST:event_keyReleased

    public void actualizarTabla(){
        mt.setRowCount(0);
           String encabezado [] = {"Nombre", "Identificacion", "Contacto", "Correo Electronico", "Cargo", "Salario", "Profesion", "Jornada Laboral", "ID"};
           mt.setColumnIdentifiers(encabezado);

           tablaEmpleados.setModel(mt);
           

           //DATOS CLIENTE
           List<Empleado> empleados = TeachStoreLJ.usuarios.listaEmpleados;

           for(Empleado empleado: empleados){
                String nombre = empleado.getNombre();
                String cedula = empleado.getCedula();
                String telefono = empleado.getTelefono();
                String email = empleado.getCorreo();
                String cargo = empleado.getCargo();
                double salario = empleado.getSalario();
                DecimalFormat fm = new DecimalFormat("#, ###");
                String salarioFormateado = fm.format(salario);
                String profesion = empleado.getProfesion();
                String jornada = empleado.getJornadaLaboral();
                String id = empleado.getId();
                
                //Validar cargo para empleado segun filtro
                String eleccionEmpleado = comboCargo.getSelectedItem().toString();
                boolean controlCargo = false;
                if(eleccionEmpleado.equals("Todos") || eleccionEmpleado.equals(cargo)){
                    controlCargo = true;
                }
                
                //Validar salario
                String eleccionSalario = comboSalario.getSelectedItem().toString();
                boolean controladorSalario = false;
                if(eleccionSalario.equals("Todos")){
               controladorSalario = true;
                } else if(eleccionSalario.equals("Minimo") && salario == 1423500){
                    controladorSalario = true;
                } else if(eleccionSalario.equals("$1.500.000 $1.999.999") && salario >= 1500000 && salario <= 1999999){
                    controladorSalario = true;
                } else if(eleccionSalario.equals("$2.000.000 - $2.999.999") && salario >= 2000000 && salario <= 2999999){
                    controladorSalario = true;
                } else if(eleccionSalario.equals("$3.000.000 - $4.999.99") && salario >= 3000000 && salario <= 4999999){
                    controladorSalario = true;
                } else if(eleccionSalario.equals("$5.000.000 - $9.999.999") && salario >= 5000000 && salario <= 9999999){
                    controladorSalario = true;
                } else if(eleccionSalario.equals("$10.000.000 o má") && salario >= 510000000){
                    controladorSalario = true;
                } else{
                    controladorSalario = false;
                }
                
                //Validar jornada laboral segun filtro
                String eleccionJornada = comboJornada.getSelectedItem().toString();
                boolean controlJornada = false;
                if (eleccionJornada.equals("Todos") || eleccionJornada.equals(jornada)){
                    controlJornada = true;
                }
                
               if(nombre.startsWith(txtNombre.getText()) &&
                    cedula.startsWith(txtIdentificacion.getText()) &&
                    telefono.startsWith(txtContacto.getText()) &&
                    email.startsWith(txtCorreo.getText()) &&
                    controlCargo &&
                    controladorSalario &&
                    profesion.startsWith(txtProfesion.getText()) &&
                    controlJornada &&
                    id.startsWith(txtId.getText())){
                   mt.addRow(new Object[] {nombre, cedula, telefono, email, cargo, salarioFormateado, profesion, jornada, id});
               }
           }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JComboBox<String> comboJornada;
    private javax.swing.JComboBox<String> comboSalario;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProfesion;
    // End of variables declaration//GEN-END:variables
}
