/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Productos;

import Clases.*;
import MeException.*;
import java.util.*;
import com.mycompany.teachstorelj.TeachStoreLJ;
import java.text.DecimalFormat;
import java.time.Duration;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class EliminarSDigitalFrame extends javax.swing.JFrame {

    Frames recargarPagina = new Frames();
    DefaultTableModel mt  = new DefaultTableModel();
    
    public EliminarSDigitalFrame() {
        initComponents();
        
        //Cargamos Servicios a mmodificar
        List<ServicioDigital> servicioDigital = TeachStoreLJ.inventario.listaSDigitales;
        
        for(ServicioDigital servicio: servicioDigital){
            comboSDigitales.addItem(servicio);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        comboSDigitales = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        btnEliminarSDigital = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSDigital = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel14.setBackground(new java.awt.Color(30, 30, 46));

        jLabel103.setBackground(new java.awt.Color(255, 255, 255));
        jLabel103.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(238, 238, 238));
        jLabel103.setText("TechStore");

        jLabel104.setBackground(new java.awt.Color(255, 255, 255));
        jLabel104.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(238, 238, 238));
        jLabel104.setText("Eliminar Servicio Digital");

        comboSDigitales.setBackground(new java.awt.Color(59, 63, 66));
        comboSDigitales.setForeground(new java.awt.Color(255, 255, 255));
        comboSDigitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSDigitalesActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(59, 63, 66));

        btnEliminarSDigital.setBackground(new java.awt.Color(39, 241, 82));
        btnEliminarSDigital.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarSDigital.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarSDigital.setText("Eliminar");
        btnEliminarSDigital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminarSDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSDigitalActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio(evt);
            }
        });

        tablaSDigital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Categoria", "Duracion", "Descripcion", "Técnico Responsable", "Codigo"
            }
        ));
        jScrollPane2.setViewportView(tablaSDigital);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEliminarSDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarSDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboSDigitales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel103)
                            .addComponent(jLabel104))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel104)
                .addGap(18, 18, 18)
                .addComponent(comboSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSDigitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSDigitalesActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_comboSDigitalesActionPerformed

    private void btnEliminarSDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSDigitalActionPerformed
        //Segun el SERVICIO elegido, lo eliminamos de la lista
        ServicioDigital servicioEliminar = (ServicioDigital) comboSDigitales.getSelectedItem();

        TeachStoreLJ.inventario.listaSDigitales.remove(servicioEliminar);
        JOptionPane.showMessageDialog(null, "Servicio Digital  Eliminado", "Creacion Producto", JOptionPane.HEIGHT);

        dispose();
        recargarPagina.recargarEliminarSDigital();
    }//GEN-LAST:event_btnEliminarSDigitalActionPerformed

    private void btnInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnInicio

private void actualizarTabla(){
        //Cada escoge un servicio se muestra le informacion de este
        //Cada que escoga un servicio diferente la tabla debe actualizarce 
        mt.setRowCount(0);
        String encabezado [] = {"Nombre", "Precio", "Categoria", "Duracion", "Descripcion", "Tecnico Responsable", "Codigo"};
        mt.setColumnIdentifiers(encabezado);
        
        tablaSDigital.setModel(mt);
        
        ServicioDigital servicioEliminar = (ServicioDigital) comboSDigitales.getSelectedItem();
        
        
        String nombre = servicioEliminar.getNombre();
        double precio = servicioEliminar.getPrecio();
        DecimalFormat fm = new DecimalFormat("#, ###");
        String precioFormateado = fm.format(precio);
        String categoria = servicioEliminar.getCategoria();
        String duracion = (String.valueOf(servicioEliminar.getDuracionEstimada().toMinutes()));
        String descripcion = servicioEliminar.getDescripcion();
        Tecnico tecnicoR = servicioEliminar.getTecnicoResponsable();
        String id = servicioEliminar.getId();
        
        mt.addRow(new Object[] {nombre, precioFormateado, categoria, duracion, descripcion, tecnicoR, id});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarSDigital;
    private javax.swing.JButton btnInicio;
    private javax.swing.JComboBox<ServicioDigital> comboSDigitales;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaSDigital;
    // End of variables declaration//GEN-END:variables
}
