/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Productos;

import Clases.*;
import MeException.CampoVacioException;
import MeException.NumeroFueraDeLimitesException;
import MeException.TiempoNoPermitidoException;
import java.util.*;
import com.mycompany.teachstorelj.TeachStoreLJ;
import java.text.DecimalFormat;
import java.time.Duration;
import javax.swing.JOptionPane;

public class ModificarSDigitalesFrame extends javax.swing.JFrame {

    Frames recargarPagina = new Frames();
    public ModificarSDigitalesFrame() {
        initComponents();
        //Cargamos Servicios a mmodificar
        List<ServicioDigital> servicioDigital = TeachStoreLJ.inventario.listaSDigitales;
        
        for(ServicioDigital servicio: servicioDigital){
            comboSDigitales.addItem(servicio);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        comboSDigitales = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        txtDuracion = new javax.swing.JTextField();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnModificarServicio = new javax.swing.JButton();
        jLabel120 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        jLabel123 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        comboTecnicos2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel14.setBackground(new java.awt.Color(30, 30, 46));

        jLabel103.setBackground(new java.awt.Color(255, 255, 255));
        jLabel103.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(238, 238, 238));
        jLabel103.setText("TechStore");

        jLabel104.setBackground(new java.awt.Color(255, 255, 255));
        jLabel104.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(238, 238, 238));
        jLabel104.setText("Modificar Servicio Digital");

        comboSDigitales.setBackground(new java.awt.Color(59, 63, 66));
        comboSDigitales.setForeground(new java.awt.Color(255, 255, 255));
        comboSDigitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSDigitalesActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(59, 63, 66));

        txtDuracion.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N

        jLabel117.setBackground(new java.awt.Color(255, 255, 255));
        jLabel117.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(238, 238, 238));
        jLabel117.setText("Tecnico Responsable");

        jLabel118.setBackground(new java.awt.Color(255, 255, 255));
        jLabel118.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(238, 238, 238));
        jLabel118.setText("Descripcion");

        txtDescripcion.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtDescripcion.setText("0");

        btnModificarServicio.setBackground(new java.awt.Color(39, 241, 82));
        btnModificarServicio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnModificarServicio.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarServicio.setText("Modificar");
        btnModificarServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnModificarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarServicioActionPerformed(evt);
            }
        });

        jLabel120.setBackground(new java.awt.Color(255, 255, 255));
        jLabel120.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(238, 238, 238));
        jLabel120.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        txtPrecio.setText("0");

        jLabel121.setBackground(new java.awt.Color(255, 255, 255));
        jLabel121.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(238, 238, 238));
        jLabel121.setText("Precio");

        jLabel122.setBackground(new java.awt.Color(255, 255, 255));
        jLabel122.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(238, 238, 238));
        jLabel122.setText("Categoria");

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio(evt);
            }
        });

        jLabel123.setBackground(new java.awt.Color(255, 255, 255));
        jLabel123.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(238, 238, 238));
        jLabel123.setText("Duracion");

        comboCategoria.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mantemiento y reparación", "Software y sistemas", "Redes y conectividad", "Asesoria y soporte técnico" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        comboTecnicos2.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        comboTecnicos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTecnicos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnModificarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(comboTecnicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(316, 316, Short.MAX_VALUE))
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel15Layout.createSequentialGroup()
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel118)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel117)
                                    .addGap(22, 22, 22))
                                .addGroup(jPanel15Layout.createSequentialGroup()
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel120)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel121)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel15Layout.createSequentialGroup()
                                    .addComponent(jLabel122)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel123)
                                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap()))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(comboTecnicos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnModificarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(jLabel120)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(jLabel121)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel122)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(jLabel123)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                            .addComponent(jLabel118)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel117))
                    .addGap(80, 80, 80)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel103)
                        .addGap(0, 344, Short.MAX_VALUE))
                    .addComponent(comboSDigitales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel104)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel104)
                .addGap(18, 18, 18)
                .addComponent(comboSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSDigitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSDigitalesActionPerformed
        //Cargamos los tecnico y agregamos el comboBox tecnicos
        List<Empleado> empleados = TeachStoreLJ.usuarios.listaEmpleados;
        
        for(Empleado tecnico: empleados){
            if(tecnico.getCargo().equals("Tecnico")){
                comboTecnicos2.addItem(tecnico);
            }
        }

        //Segun el servicio elegio aparece la informacion, si desea modificar simplemente borra y coloca el nuevo dato
        ServicioDigital servicioElegido = (ServicioDigital) comboSDigitales.getSelectedItem();

        txtNombre.setText(servicioElegido.getNombre());
        DecimalFormat fm = new DecimalFormat("#, ###");
        double precio = servicioElegido.getPrecio();
        String precioFormateado = fm.format(precio);
        
        txtPrecio.setText(precioFormateado);
        comboCategoria.setSelectedItem(servicioElegido.getCategoria());
        txtDuracion.setText(String.valueOf(servicioElegido.getDuracionEstimada().toMinutes())); 
        txtDescripcion.setText(servicioElegido.getDescripcion());
        
        comboTecnicos2.setSelectedItem(servicioElegido.getTecnicoResponsable());
    }//GEN-LAST:event_comboSDigitalesActionPerformed

    private void btnModificarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarServicioActionPerformed
        //Abstraemos  cada dato ingresado por el usuario
        String nombre = txtNombre.getText();
        double precio = recargarPagina.convertirPrecio(txtPrecio.getText());
        String categoria = comboCategoria.getSelectedItem().toString();
        long duracionLong = recargarPagina.convertirLong(txtDuracion.getText(), "Hora");
        Duration duracion = Duration.ofMinutes(0);
        if(duracionLong != -1){
            duracion = Duration.ofMinutes(duracionLong);
        }
        String descripcion = txtDescripcion.getText();
        Tecnico tecnicoResponsable = (Tecnico) comboTecnicos2.getSelectedItem(); 
        
        //Servicio a modificar
        ServicioDigital servicioModificar = (ServicioDigital) comboSDigitales.getSelectedItem();
        
        //Realizamos cambios
        try{
            servicioModificar.modificarServicio(nombre, precio, categoria, duracion, descripcion, tecnicoResponsable);
            servicioModificar.mostrarInfo();
            JOptionPane.showMessageDialog(null, "SE A MODIFICADO EL SERVICIO", "Servicio Modificado", JOptionPane.INFORMATION_MESSAGE);
            
            dispose();
            recargarPagina.recargarModificarSDigital();
        } catch (CampoVacioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR CAMPO VACIO", JOptionPane.ERROR_MESSAGE);
        } catch(TiempoNoPermitidoException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "TIEMPO NO VALIDO", JOptionPane.ERROR_MESSAGE);
        } catch(NumeroFueraDeLimitesException ex){
            //Verificamos que ningun número sobrepase el rango
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR NUMERO MENOR A 0", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarServicioActionPerformed

    private void btnInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio
        //Boton inicio
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnInicio

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void comboTecnicos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTecnicos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTecnicos2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnModificarServicio;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<ServicioDigital> comboSDigitales;
    private javax.swing.JComboBox<Empleado> comboTecnicos2;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
