/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Productos;

import Clases.*;

public class ServicioDigitalFrame extends javax.swing.JFrame {

    Frames recargarPagina = new Frames();
    
    public ServicioDigitalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnModificarSDigitales = new javax.swing.JButton();
        btnAgregarSDigitales = new javax.swing.JButton();
        btnEliminarSDigitales = new javax.swing.JButton();
        btnVerSDigitales = new javax.swing.JButton();
        btnModificarProducto2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("TechStore");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Servicio Digital");

        btnModificarSDigitales.setBackground(new java.awt.Color(39, 241, 82));
        btnModificarSDigitales.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnModificarSDigitales.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarSDigitales.setText("Modificar S. Digital");
        btnModificarSDigitales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnModificarSDigitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSDigitalesActionPerformed(evt);
            }
        });

        btnAgregarSDigitales.setBackground(new java.awt.Color(39, 241, 82));
        btnAgregarSDigitales.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnAgregarSDigitales.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarSDigitales.setText("Agregar S. Digital");
        btnAgregarSDigitales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAgregarSDigitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSDigitalesActionPerformed(evt);
            }
        });

        btnEliminarSDigitales.setBackground(new java.awt.Color(39, 241, 82));
        btnEliminarSDigitales.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarSDigitales.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarSDigitales.setText("Eliminar S. Digital");
        btnEliminarSDigitales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminarSDigitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSDigitalesActionPerformed(evt);
            }
        });

        btnVerSDigitales.setBackground(new java.awt.Color(39, 241, 82));
        btnVerSDigitales.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnVerSDigitales.setForeground(new java.awt.Color(0, 0, 0));
        btnVerSDigitales.setText("Ver S. Ditiales");
        btnVerSDigitales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVerSDigitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSDigitalesActionPerformed(evt);
            }
        });

        btnModificarProducto2.setBackground(new java.awt.Color(39, 241, 82));
        btnModificarProducto2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnModificarProducto2.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarProducto2.setText("Inicio");
        btnModificarProducto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnModificarProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProducto2btnInicio(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnModificarProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregarSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificarSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEliminarSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVerSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarSDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnModificarProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarSDigitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSDigitalesActionPerformed
        //Boton pagian modificar producto
        dispose();
        recargarPagina.recargarModificarSDigital();
    }//GEN-LAST:event_btnModificarSDigitalesActionPerformed

    private void btnAgregarSDigitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSDigitalesActionPerformed
        //Boton pagina agregar producto
        dispose();
        recargarPagina.recargarAgregarSDigital();
    }//GEN-LAST:event_btnAgregarSDigitalesActionPerformed

    private void btnEliminarSDigitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSDigitalesActionPerformed
        //Boton pagina eliminar producto
        dispose();
        recargarPagina.recargarEliminarSDigital();
    }//GEN-LAST:event_btnEliminarSDigitalesActionPerformed

    private void btnVerSDigitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSDigitalesActionPerformed
        //Boton pagina ver productos
        dispose();
        recargarPagina.recargarVerSDigitales();
    }//GEN-LAST:event_btnVerSDigitalesActionPerformed

    private void btnModificarProducto2btnInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProducto2btnInicio
        //Boton pagina principal
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnModificarProducto2btnInicio


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSDigitales;
    private javax.swing.JButton btnEliminarSDigitales;
    private javax.swing.JButton btnModificarProducto2;
    private javax.swing.JButton btnModificarSDigitales;
    private javax.swing.JButton btnVerSDigitales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
