/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Productos;

import Clases.Frames;

import Clases.*;
import java.util.*;
import com.mycompany.teachstorelj.*;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

public class VerSDigitalesFrame extends javax.swing.JFrame {

    Frames recargarPagina = new Frames();
    DefaultTableModel mt  = new DefaultTableModel();
    
    public VerSDigitalesFrame() {
        initComponents();
        
        //Se actualiza la tabla
        actualizarTabla();
        
        //Agregamos los items al filtro de precio
        comboPrecio.addItem("$0 - $499.999");
        comboPrecio.addItem("$500.000 - $1.499.999");
        comboPrecio.addItem("$1.500.000 - $2.999.999");
        comboPrecio.addItem("$3.000.000 - $4.999.999");
        comboPrecio.addItem("$5.000.000 - $9.999.999");
        comboPrecio.addItem("$10.000.000 o más"); 
        
        //Agregamos los items para el filtro de duracion
        comboDuracion.addItem("30-59 (MIN)");
        comboDuracion.addItem("60-89 (MIN)");
        comboDuracion.addItem("90-119 (MIN)");
        comboDuracion.addItem("120-149 (MIN)");
        comboDuracion.addItem("150-179 (MIN)");
        comboDuracion.addItem("180 o más (MIN)");
        
        //Cargamos los tecnico y agregamos el comboBox tecnicos
        List<Empleado> empleados = TeachStoreLJ.usuarios.listaEmpleados;
        
        for(Empleado tecnico: empleados){
            if(tecnico.getCargo().equals("Tecnico")){
                comboTecnicos.addItem(tecnico.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSDigitales = new javax.swing.JTable();
        btnInicio = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        comboPrecio = new javax.swing.JComboBox<>();
        comboCategoria = new javax.swing.JComboBox<>();
        txtDescripcion = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        comboTecnicos = new javax.swing.JComboBox<>();
        comboDuracion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("TechStore");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("Servicios Digitales");

        tablaSDigitales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Categoria", "Duracion (min)", "Descripcion", "Técnico Responsable", "Codigo"
            }
        ));
        jScrollPane1.setViewportView(tablaSDigitales);

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(59, 63, 66));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKetReleased(evt);
            }
        });

        comboPrecio.setBackground(new java.awt.Color(59, 63, 66));
        comboPrecio.setForeground(new java.awt.Color(255, 255, 255));
        comboPrecio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        comboPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrecioActionPerformed(evt);
            }
        });

        comboCategoria.setBackground(new java.awt.Color(59, 63, 66));
        comboCategoria.setForeground(new java.awt.Color(255, 255, 255));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mantenimiento y reparación", "Software y sistemas", "Redes y conectividad", "Asesoria y soporte técnico", " " }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        txtDescripcion.setBackground(new java.awt.Color(59, 63, 66));
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKetReleased(evt);
            }
        });

        txtCodigo.setBackground(new java.awt.Color(59, 63, 66));
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setText("SR-DIGITAL-00");
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKetReleased(evt);
            }
        });

        comboTecnicos.setBackground(new java.awt.Color(59, 63, 66));
        comboTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        comboTecnicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        comboTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTecnicosActionPerformed(evt);
            }
        });

        comboDuracion.setBackground(new java.awt.Color(59, 63, 66));
        comboDuracion.setForeground(new java.awt.Color(255, 255, 255));
        comboDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        comboDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDuracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comboPrecio)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion)
                            .addComponent(comboTecnicos)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(comboDuracion))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        //Boton inicio
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtNombreKetReleased

    private void comboPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrecioActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_comboPrecioActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtDescripcionKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtDescripcionKetReleased

    private void txtCodigoKetReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKetReleased
        actualizarTabla();
    }//GEN-LAST:event_txtCodigoKetReleased

    private void comboTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTecnicosActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_comboTecnicosActionPerformed

    private void comboDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDuracionActionPerformed
         actualizarTabla();
    }//GEN-LAST:event_comboDuracionActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void actualizarTabla(){
        //Actualizamos al tabla segun los filtros deseados
        mt.setRowCount(0);
        String encabezado [] = {"Nombre", "Precio", "Categoria", "Duracion", "Descripcion", "Tecnico Responsable", "Codigo"};
        mt.setColumnIdentifiers(encabezado);
        
        tablaSDigitales.setModel(mt);
        
        List<ServicioDigital> serviciosDigitales = TeachStoreLJ.inventario.listaSDigitales;
        
        
        for(ServicioDigital servicio : serviciosDigitales) {
           String nombre = servicio.getNombre();
           double precio = servicio.getPrecio();
           DecimalFormat fm = new DecimalFormat("#, ###");
           String precioFormateado = fm.format(precio);
           String categoria = servicio.getCategoria();
           String duracion = (String.valueOf(servicio.getDuracionEstimada().toMinutes()));
           String descripcion = servicio.getDescripcion();
           Tecnico tecnicoR = servicio.getTecnicoResponsable();
           String id = servicio.getId();
           
           //Validacion para el precio solicitado
          String eleccionPrecio = comboPrecio.getSelectedItem().toString();
           boolean controladorPrecio;
            if(eleccionPrecio.equals("Todos")){
               controladorPrecio = true;
           } else if(eleccionPrecio.equals("$0 - $499.999") && precio >= 0 && precio <= 499999){
               controladorPrecio = true;
           } else if(eleccionPrecio.equals("$500.000 - $1.499.999") && precio >= 500000 && precio <= 1499999){
               controladorPrecio = true;
           } else if(eleccionPrecio.equals("$1.500.000 - $2.999.999") && precio >= 1500000 && precio <= 2999999){
               controladorPrecio = true;
           } else if(eleccionPrecio.equals("$3.000.000 - $4.999.99") && precio >= 3000000 && precio <= 4999999){
               controladorPrecio = true;
           } else if(eleccionPrecio.equals("$5.000.000 - $9.999.999") && precio >= 5000000 && precio <= 9999999){
               controladorPrecio = true;
           } else if(eleccionPrecio.equals("$10.000.000 o má") && precio >= 510000000){
               controladorPrecio = true;
           } else{
               controladorPrecio = false;
           }
           
           //Validar categoria escogida
           String eleccioCategoria = comboCategoria.getSelectedItem().toString();
           boolean controlCategoria = false;
           if(eleccioCategoria.equals("Todos") || eleccioCategoria.equals(categoria)){
               controlCategoria = true;
           }
           
           //Validar duracion escogida
           String eleccionDuracion = comboDuracion.getSelectedItem().toString();
           boolean controlDuracion;
           int numDuracion = Integer.parseInt(duracion);
           if(eleccionDuracion.equals("Todos")){
               controlDuracion  = true;
           } else if(eleccionDuracion.equals("30-59 (MIN)") && numDuracion >= 30 && numDuracion <= 59){
               controlDuracion  = true;
           } else if(eleccionDuracion.equals("60-89 (MIN)") && numDuracion >= 60 && numDuracion <= 89){
               controlDuracion  = true;
           } else if(eleccionDuracion.equals("90-119 (MIN)") && numDuracion >= 90 && numDuracion <= 119){
               controlDuracion  = true;
           } else if(eleccionDuracion.equals("120-149 (MIN)") && numDuracion >= 120 && numDuracion <= 149){
               controlDuracion  = true;
           } else if(eleccionDuracion.equals("150-179 (MIN)") && numDuracion >= 150 && numDuracion <= 179){
               controlDuracion  = true;
           } else if(eleccionDuracion.equals("180 o más (MIN)") && numDuracion >= 180){
               controlDuracion  = true;
           } else{
               controlDuracion  = false;
           }
         
          
           //Validar combo tecnicos
           String eleccionTecnicos = comboTecnicos.getSelectedItem().toString();
           boolean controlTecnico = false;
            if(eleccionTecnicos.equalsIgnoreCase("Todos") || eleccionTecnicos.equalsIgnoreCase(tecnicoR.toString())){
                controlTecnico = true;
            }

           if(nombre.startsWith(txtNombre.getText()) && 
                   controladorPrecio &&
                   controlCategoria &&
                   controlDuracion &&
                   descripcion.startsWith(txtDescripcion.getText()) &&
                   id.startsWith(txtCodigo.getText()) &&
                   controlTecnico){
               mt.addRow(new Object[] {nombre, precioFormateado, categoria, duracion, descripcion, tecnicoR, id});
           }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboDuracion;
    private javax.swing.JComboBox<String> comboPrecio;
    private javax.swing.JComboBox<String> comboTecnicos;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSDigitales;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
