/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Lucerito
 */
public class InventarioFrame extends javax.swing.JFrame {

    /**
     * Creates new form InventarioFrame
     */
    public InventarioFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCrearProducto1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonCrearProducto4 = new javax.swing.JButton();
        buttonCrearProducto7 = new javax.swing.JButton();
        buttonCrearProducto8 = new javax.swing.JButton();
        buttonCrearProducto9 = new javax.swing.JButton();

        buttonCrearProducto1.setBackground(new java.awt.Color(39, 241, 82));
        buttonCrearProducto1.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        buttonCrearProducto1.setForeground(new java.awt.Color(0, 0, 0));
        buttonCrearProducto1.setText("Inventario");
        buttonCrearProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearProducto1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        jLabel2.setBackground(new java.awt.Color(238, 238, 238));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setText("TechStore");

        jLabel1.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setText("Inventario");

        buttonCrearProducto4.setBackground(new java.awt.Color(39, 241, 82));
        buttonCrearProducto4.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        buttonCrearProducto4.setForeground(new java.awt.Color(0, 0, 0));
        buttonCrearProducto4.setText("Modificar Producto");
        buttonCrearProducto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonCrearProducto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearProducto4ActionPerformed(evt);
            }
        });

        buttonCrearProducto7.setBackground(new java.awt.Color(39, 241, 82));
        buttonCrearProducto7.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        buttonCrearProducto7.setForeground(new java.awt.Color(0, 0, 0));
        buttonCrearProducto7.setText("Agregar Producto");
        buttonCrearProducto7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonCrearProducto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearProducto7ActionPerformed(evt);
            }
        });

        buttonCrearProducto8.setBackground(new java.awt.Color(39, 241, 82));
        buttonCrearProducto8.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        buttonCrearProducto8.setForeground(new java.awt.Color(0, 0, 0));
        buttonCrearProducto8.setText("Eliminar Producto");
        buttonCrearProducto8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonCrearProducto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearProducto8ActionPerformed(evt);
            }
        });

        buttonCrearProducto9.setBackground(new java.awt.Color(39, 241, 82));
        buttonCrearProducto9.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        buttonCrearProducto9.setForeground(new java.awt.Color(0, 0, 0));
        buttonCrearProducto9.setText("Ver Producto");
        buttonCrearProducto9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonCrearProducto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearProducto9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonCrearProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonCrearProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonCrearProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonCrearProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrearProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCrearProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrearProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCrearProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCrearProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearProducto1ActionPerformed

    private void buttonCrearProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearProducto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearProducto4ActionPerformed

    private void buttonCrearProducto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearProducto7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearProducto7ActionPerformed

    private void buttonCrearProducto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearProducto8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearProducto8ActionPerformed

    private void buttonCrearProducto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearProducto9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearProducto9ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCrearProducto1;
    private javax.swing.JButton buttonCrearProducto4;
    private javax.swing.JButton buttonCrearProducto7;
    private javax.swing.JButton buttonCrearProducto8;
    private javax.swing.JButton buttonCrearProducto9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
