/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.*;
import com.mycompany.teachstorelj.TeachStoreLJ;
import javax.swing.JOptionPane;

public class ReportesFrame extends javax.swing.JFrame {

    Frames recargarPagina = new Frames();
    public ReportesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVentaCajeros = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnStockBajo = new javax.swing.JButton();
        btnProductosVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        jLabel1.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Reportes");

        btnVentaCajeros.setBackground(new java.awt.Color(39, 241, 82));
        btnVentaCajeros.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnVentaCajeros.setForeground(new java.awt.Color(0, 0, 0));
        btnVentaCajeros.setText("Reporte Ventas Cajeros");
        btnVentaCajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVentaCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaCajerosActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(39, 241, 82));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciobtnInicio(evt);
            }
        });

        btnStockBajo.setBackground(new java.awt.Color(39, 241, 82));
        btnStockBajo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnStockBajo.setForeground(new java.awt.Color(0, 0, 0));
        btnStockBajo.setText("Reporte Productos Con Stock Bajo");
        btnStockBajo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnStockBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockBajoActionPerformed(evt);
            }
        });

        btnProductosVenta.setBackground(new java.awt.Color(39, 241, 82));
        btnProductosVenta.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnProductosVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnProductosVenta.setText("Reporte Venta Productos");
        btnProductosVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProductosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStockBajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVentaCajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProductosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVentaCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaCajerosActionPerformed
        TeachStoreLJ.csv.generarReporteVentasCajeros();
        JOptionPane.showMessageDialog(null, "YA PUEDES BUSCAR EL ARCHVIO DEL REPORTE", "REPORTE CREADO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVentaCajerosActionPerformed

    private void btnIniciobtnInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciobtnInicio
        //Boton volver a inicio
        dispose();
        recargarPagina.recargarMainFrame();
    }//GEN-LAST:event_btnIniciobtnInicio

    private void btnStockBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockBajoActionPerformed
        TeachStoreLJ.csv.generarReporteProductosStockBajo();
        JOptionPane.showMessageDialog(null, "YA PUEDES BUSCAR EL ARCHVIO DEL REPORTE", "REPORTE CREADO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnStockBajoActionPerformed

    private void btnProductosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosVentaActionPerformed
        TeachStoreLJ.csv.generarReporteVentaProductos();
        JOptionPane.showMessageDialog(null, "YA PUEDES BUSCAR EL ARCHVIO DEL REPORTE", "REPORTE CREADO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnProductosVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnProductosVenta;
    private javax.swing.JButton btnStockBajo;
    private javax.swing.JButton btnVentaCajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
